Default: &defaults
  database: Hamyr.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Hamyr_test.sqlite3
  <<: *defaults

Staging:
  database: Hamyr_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Hamyr_production.sqlite3
  poolsize: 100
  <<: *defaults
